### PR TITLE
Corrected base class inheritance.

### PR DESCRIPTION
**Pull request by gergo-debreczeni**

### CODE REVIEW

**Comment by thenoizz** [comment]
YOLO

**Comment by alexpilotti** [comment]
Sorry mate, I have to close the PR. This has been fixed in the upstream repo since some time.

Nevertheless, in order to thank you for this valuable effort, you will receive a precious and unique 3d printed gadget signed by our creative director!

**Comment by thenoizz** [comment]
He wants a summit ticket !

Sent from a galaxy far, far away...

On 17 mar. 2016, at 17:26, Alessandro Pilotti <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry mate, I have to close the PR. This has been fixed in the upstream repo since some time.

Nevertheless, in order to thank you for this valuable effort, you will receive a precious and unique 3d printed gadget signed by our creative director!

**Comment by gergo-debreczeni** [comment]
Nooo, how else am I supposed to meet my open source contribution quota ? :(
Oh well, let's hunt some openstack low hanging fruits :strawberry:

**Comment by ader1990** [comment]
Soon to come, Readme typos PRs! I can feel it...

**Pull request closed without merging**
